# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5132

@Username=administrator@gmail.com
@Password=Administrator@123
@BearerToken=CfDJ8MwLMifcxcdGm3jtD7E8hteTrSvnIR7alNPdpcj0Yeoi9dKpdcO9rvL7E0qH0F-rVjO_uY1EXc4oiNqRmYhvGKHMmqFwIZo3upMZmtTIJf7AUEqA2r-zC_om9sfH15VnpHHd5T_EROgLiDMM6fvak46YuOtWdo_8ZVFZw83b13C4CfX9_TwlNCzdHBBlQs2jpZGtnK1NT9OFmAex0qsLR00nm3AfBZkEvTmijRBbgcvndCDoZ91yi-QxZ83v9DQetgw9QXJ_HYHEtXAT71v1F_IEjKBAhk5RjJYavVczW_lC9RVjVi8yGBFr2Kuzp3Zzab4AA7oRfnNmjpbO3Ajm96OAjIEq9wnjCfYC1H2w8WceffeYTecDIb-2xC_NQ1W2bwJXsD_XXiy0UdQGyC-l7gF9Xs_0kOExfzzdpRVup_H4-pEQLQ6bmQUPCEo8n4nw9Ha1KtDCmCne-uNpl92kqb4TSkUStm-J0pTpKP9GvCTXB0aVizcxYDbbGerEfBo4UE5SZFlxj3SXOBzp8EBdyevS73YjiI0kJ8s6VhmNZLh1qyi1ZAxtztCiTnInpsTZFVtkBWX-YCPFt4CorJe2_0CvUSb3A8DGJu9zYlUlC681DSbHhghOOWZoa7h9x5chwAvmWPCX_rYJBgk7orSICRKVXdZqjoN60JDKg7feqfH0UONbhV8F-eBJ4fNWNSTs_w

# POST Users Register
POST {{Web_HostAddress}}/api/Users/Register
Content-Type: application/json

{
  "username": {{{Username}}},
  "password": {{{Password}}},
  "email": {{{Username}}}
}

###

# POST Users Login
POST {{Web_HostAddress}}/api/Users/Login
Content-Type: application/json

{
  "username": "administrator@gmail.com",
  "password": "Administrator@123",
  "email": "administrator@gmail.com"
}

###

# POST Users Refresh
POST {{Web_HostAddress}}/api/Users/Refresh
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "refreshToken": ""
}

###

# GET WeatherForecast
GET {{Web_HostAddress}}/api/WeatherForecasts
Authorization: Bearer {{BearerToken}}

###

# GET Rooms
GET {{Web_HostAddress}}/api/Rooms
Authorization: Bearer {{BearerToken}}

###

# Create Speakers

POST {{Web_HostAddress}}/api/Speaker
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "Id":"250b7a75-c2a3-4283-bd24-517c8544a87f",
  "University":"University of Washington",
  "JobTitle":"Software Engineer"
}

###

###

# Create Sessions

POST {{Web_HostAddress}}/api/Sessions
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "Topic":"Nature",
  "ConfDate":"2024-02-02",
  "StartTime":"08:00:00",
  "EndTime" : "17:00:00",
  "SpeakerId":"250b7a75-c2a3-4283-bd24-517c8544a87f",
  "RoomId" : "bb820f75-fa6a-44b5-1aa2-08dc2abaa4ea"
}

###

# Create Rooms
POST {{Web_HostAddress}}/api/Rooms
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "capacity":50,
  "available":"No"
}

###