# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5132

// Admin
@Username=Speaker@gmail.com
@Password=Speaker@123
@BearerToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNlYjgzNjVhLTkwYmItNDM4ZS1iZjkwLTdiYzAxYWI5YzhlZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiM2ViODM2NWEtOTBiYi00MzhlLWJmOTAtN2JjMDFhYjljOGVlIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU1BFQUtFUiIsImV4cCI6MTcwODIyNzk1MywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTEzMiIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjUxMzIifQ.7t3_CxCphvlJWnVyuMNBNoy4V9l-VPtzcyTVgO2LPcI

# POST Users Register
POST {{Web_HostAddress}}/api/Users/Register
Content-Type: application/json

{
  "UserName": "Speaker@gmail.com",
  "Password": "Speaker@123",
  "Email": "Speaker@gmail.com",
  "PhoneNumber": "123456789",
  "FirstName": "Speaker",
  "LastName": "Speaker",
  "Gender": "Male"
}

###

# POST Users Login
POST {{Web_HostAddress}}/api/Users/Login
Content-Type: application/json

{
  "username": "{{Username}}",
  "password": "{{Password}}",
  "email": "{{Username}}"
}

###

###



# Create Rooms
POST {{Web_HostAddress}}/api/Rooms
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "capacity":75,
  "available":"Yes"
}

###

# GET Rooms
GET {{Web_HostAddress}}/api/Rooms
Authorization: Bearer {{BearerToken}}

###

# Create Speakers
POST {{Web_HostAddress}}/api/Speaker
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "Id":"3eb8365a-90bb-438e-bf90-7bc01ab9c8ee",
  "University":"University of Washington",
  "JobTitle":"Software Engineer"
}

###

# Create Sessions
POST {{Web_HostAddress}}/api/Sessions
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "Topic":"Nature",
  "ConfDate":"2024-02-20",
  "StartTime":"08:00:00",
  "EndTime" : "17:00:00",
  "SpeakerId":"3eb8365a-90bb-438e-bf90-7bc01ab9c8ee",
  "RoomId" : "a1a5188b-16f0-49e8-9734-0978e3177727"
}

###

###

# Get Sessions
GET  {{Web_HostAddress}}/api/Sessions
Authorization: Bearer {{BearerToken}}


###