# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5132

// Admin
@Username=administrator@gmail.com
@Password=Administrator@123
@BearerToken=CfDJ8MwLMifcxcdGm3jtD7E8htePdHhshmLHRjZ8OJ6xprQPHqmDMgtMDn0ZliBC58m4OO35YB0o2TqpRuWzTA5nvSyLwX+WSdPBb5OchhCy3iutFYxTFdTw8vgAcNp9Ak8Jk3p2RX7YtTl7GTgAKI3B5CGvGHwEjB6RqbM+G0SeAHBNlf/njscZTYW2XpDSa6c4+miZMFQ3d85vUNHV518G6K8aDu1wWJ9ARZ8f17IZsQ/8U8cXwivtsjDYJJP57nwdNw==

# @Username=Speaker@gmail.com
# @Password=Speaker@123
# @Email=Speaker@gmail.com
# @FirstName=Speaker
# @LastName=Speaker
# @PhoneNumber=1234567890
# @Gender=Female
# @BearerToken=<Your Bearer Code>

# POST Users Register
POST {{Web_HostAddress}}/api/Users/Register
Content-Type: application/json

{
  "UserName": "abcxyz1@gmail.com",
  "Password": "Administrator@123",
  "Email": "abcxyz1@gmail.com",
  "PhoneNumber": "123456789",
  "FirstName": "abcxyz1",
  "LastName": "abcxyz1",
  "Gender": "Male"
}

###

# POST Users Login
POST {{Web_HostAddress}}/api/Users/Login
Content-Type: application/json

{
  "username": "{{Username}}",
  "password": "{{Password}}",
  "email": "{{Username}}"
}

###

# POST Users Refresh
POST {{Web_HostAddress}}/api/Users/Refresh
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "refreshToken": ""
}

###

# GET WeatherForecast
GET {{Web_HostAddress}}/api/WeatherForecasts
Authorization: Bearer {{BearerToken}}

###

# GET Rooms
GET {{Web_HostAddress}}/api/Rooms
Authorization: Bearer {{BearerToken}}

###

# Create Speakers
POST {{Web_HostAddress}}/api/Speaker
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "Id":"250b7a75-c2a3-4283-bd24-517c8544a87f",
  "University":"University of Washington",
  "JobTitle":"Software Engineer"
}

###

# Create Sessions
POST {{Web_HostAddress}}/api/Sessions
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "Topic":"Nature",
  "ConfDate":"2024-02-02",
  "StartTime":"08:00:00",
  "EndTime" : "17:00:00",
  "SpeakerId":"250b7a75-c2a3-4283-bd24-517c8544a87f",
  "RoomId" : "bb820f75-fa6a-44b5-1aa2-08dc2abaa4ea"
}

###

# Create Rooms
POST {{Web_HostAddress}}/api/Rooms
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "capacity":50,
  "available":"No"
}

###