# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5132

// Admin
@Username=administrator@gmail.com
@Password=Administrator@123
@BearerToken = <Your Bearer Token>

###

# POST Users Login
POST {{Web_HostAddress}}/api/Users/Login
Content-Type: application/json

{
  "username": "{{Username}}",
  "password": "{{Password}}",
  "email": "{{Username}}"
}

###

###

# GET WeatherForecast
GET {{Web_HostAddress}}/api/WeatherForecasts
Authorization: Bearer {{BearerToken}}

###

###

# Create Rooms
POST {{Web_HostAddress}}/api/Rooms
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "capacity":75,
  "available":"Yes"
}

###

###

# GET Rooms
GET {{Web_HostAddress}}/api/Rooms
Authorization: Bearer {{BearerToken}}

###

###

# Create Speakers
POST {{Web_HostAddress}}/api/Speaker
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "Id":"3eb8365a-90bb-438e-bf90-7bc01ab9c8ee",
  "University":"University of Washington",
  "JobTitle":"Software Engineer"
}

###

###

# Create Sessions
POST {{Web_HostAddress}}/api/Sessions
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "Topic":"Nature",
  "ConfDate":"2024-02-20",
  "StartTime":"08:00:00",
  "EndTime" : "17:00:00",
  "SpeakerId":"3eb8365a-90bb-438e-bf90-7bc01ab9c8ee",
  "RoomId" : "a1a5188b-16f0-49e8-9734-0978e3177727"
}

###

###

# Get Sessions
GET  {{Web_HostAddress}}/api/Session
Authorization: Bearer {{BearerToken}} abc


###

###

# Delete Sessions
DELETE {{Web_HostAddress}}/api/Sessions/19fc9093-f93c-42d7-aabb-87e0b5977b0e
Authorization: Bearer {{BearerToken}}


###