# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5132

// Admin
@Username=Speaker@gmail.com
@Password=Speaker@123
@BearerToken = <Your Bearer Token>

###

# POST Users Login
POST {{Web_HostAddress}}/api/Users/Login
Content-Type: application/json

{
  "username": "{{Username}}",
  "password": "{{Password}}",
  "email": "{{Username}}"
}

###

###

# GET Rooms
GET {{Web_HostAddress}}/api/Rooms
Authorization: Bearer {{BearerToken}}

###

###

# Get Sessions
GET  {{Web_HostAddress}}/api/Sessions
Authorization: Bearer {{BearerToken}}


###